### ISSUE TITLE
nu_eval does not work in python 3.14

### ISSUE THREAD

**Issue by Walgri** [sbyrnes321/numericalunits#21]
In python 3.14:
```
>>> nu.nu_eval("3*cm")
Traceback (most recent call last):
  File "<python-input-2>", line 1, in <module>
    nu.nu_eval("3*cm")
    ~~~~~~~~~~^^^^^^^^
  File "C:\Users\Utente\Desktop\temp_python\test_numericalunit\numericalunits.py", line 464, in nu_eval
    return _eval(ast.parse(expression, mode='eval').body)
  File "C:\Users\Utente\Desktop\temp_python\test_numericalunit\numericalunits.py", line 453, in _eval
    if isinstance(node, ast.Num):
                        ^^^^^^^
AttributeError: module 'ast' has no attribute 'Num'
```

ast.Num has been removed.

changing _def _eval(node):_ to

```
def _eval(node):
        if isinstance(node, ast.Constant):
            return node.value
....
```
seems to fix it.

**Comment by sbyrnes321** [comment]
thanks, should be fixed in the new version 1.27,  let me know if it isn’t

**Comment by Walgri** [comment]
Still does not work:

```
    return node.n
           ^^^^^^
AttributeError: 'Constant' object has no attribute 'n'
```

we need to change that line to:

`            return node.value`

**Comment by sbyrnes321** [comment]
Thanks for the pull request, it’s now incorporated into the new version 1.28. Let me know if there’s any other problems.
